version: "3"
services:
  user-service-cont:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ./:/myapp3
      - /myapp/node_modules
    environment:
      - PORT=3002
    depends_on:
      - mongo
    # networks:
    #   - ui-service-cont_uinetwork
  mongo:
    image: mongo
    # environment:
    #   - MONGO_INIT_ROOT_USERNAME=yash
    #   - MONGO_INIT_ROOT_USERNAME=mypassword  
    volumes:
      - mongo-db:/data/db3
volumes:
  mongo-db:
# networks:
#   ui-service-cont_uinetwork:
#     external: true
