version: "3"
services:
  user:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ./:/myapp3
      - /myapp3/node_modules
    environment:
      - PORT=3002
    depends_on:
      - mongouser
  mongouser:
    image: mongo
    # environment:
    #   - MONGO_INIT_ROOT_USERNAME=yash
    #   - MONGO_INIT_ROOT_USERNAME=mypassword  
    volumes:
      - mongo-db-user:/data/db3
volumes:
  mongo-db-user:
networks:
  default:
    external:
      name: bridge-network
